#!/usr/bin/env bash
# Fetch secret parameters from AWS SSM Parameter Store or Secrets Manager and write .env
# Requires: AWS CLI installed and configured, or EC2 instance role with permissions

set -euo pipefail

# Prefix in SSM where parameters are stored, e.g. /travel-app/prod
SSM_PREFIX=${SSM_PREFIX:-}
OUT_ENV=${OUT_ENV:-/home/ubuntu/app/server/.env}

if [ -z "$SSM_PREFIX" ]; then
  echo "Usage: SSM_PREFIX must be set, e.g. export SSM_PREFIX=/travel-app/prod"
  exit 1
fi

echo "Fetching secrets from SSM prefix: $SSM_PREFIX"

cat > "$OUT_ENV" <<EOF
# Auto-generated by bootstrap_ssm.sh
PORT=5000
NODE_ENV=production
EOF

for key in MONGO_URI JWT_SECRET OPENAI_API_KEY TWILIO_SID TWILIO_TOKEN TWILIO_FROM AWS_REGION S3_BUCKET; do
  echo "Fetching $key"
  val=$(aws ssm get-parameter --name "${SSM_PREFIX}/${key}" --with-decryption --query Parameter.Value --output text 2>/dev/null || true)
  if [ -n "$val" ]; then
    echo "$key=$val" >> "$OUT_ENV"
  else
    echo "# $key not found in SSM: ${SSM_PREFIX}/${key}" >> "$OUT_ENV"
  fi
done

echo "Wrote env to $OUT_ENV"
